### ISSUE TITLE
Update/correct metadata in Datacite via API/query.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#1080]
Update or correct metadata via API call for an already published nmrXiv dataset.
Related to #1064

**Comment by NishaSharma14** [comment]
Dear @tilfischer,
This is fixed, which fixes the issue #1064. Can you please check and confirm once?

https://api.datacite.org/dois/10.57992/nmrxiv.p55

Thanks,
Nisha

**Comment by tilfischer** [comment]
Dear Nisha,

looks fine now. Thank you for that!

What I really still do not like is that nmrXiv Team members are automatically added as contributors. This is not obvious and I would leave the peower to the people i.e. researchers who upload dataset should be allowed to select who is a contributor. This will otherwise lead to scientific misconduct following the DFG guidelines of good scientific practice. Please see https://github.com/NFDI4Chem/nmrxiv/discussions/948 

nmrXiv need a separate section for contributors. nmrXiv team members which be prefilled, but should be removable and movable i.e. the order should be able to change, as with the Creators/Autors. I guess this is work in progress, but I still want to highlight this here, as this might lead to, as mentioned, scientific misconduct if people are added, which had nothing to do with a submission except being part of the same nmrXiv team.

For the dataset of Mr. Cicek, I would, for instance, have prefered to have him listed as a contributor first, as he did upload the data as a member of the Lead-by-Example team, which was required that I could help him for issues he had. 

Best,
Tillmann
