### ISSUE TITLE
Study share policy leaks project info

### ISSUE THREAD

**Issue by th-jena** [NFDI4Chem/nmrxiv#218]
**Describe the bug**
If you share a study with another user and they visit the study via the shared link, they also can see the project it is a part of.

**Expected behavior**
I would expect that if a user only has permissions to see a study, they should not have access to any of the parent project information.

**Desktop:**
 - OS: macOS Monterey
 - Browser chrome
 - Version: 103.0.5060.114 (Official Build) (arm64)

**Comment by NRayya** [comment]
The issue is fixed. when the user receiving the study clicks on the project name they can see that they are not authorized:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/82588017/187183185-9c539eb4-d889-4a50-952e-cfcceccc4c24.png">

However, this user can still see the project name

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/82588017/187183026-c6cb335e-4eaa-4fc9-808f-d853b08ec7de.png">
