### ISSUE TITLE
Data upload fails with projects containing jdx and jdf files

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#471]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/82588017/193152809-d9fc1d56-84b4-4d66-abc3-7e6233351114.png">

**Comment by CS76** [comment]
This is due to space (prefix) in the file names that are being uploaded. Please ensure that the file names have no trailing empty spaces. Also, nmrXiv webapp will trim the name when processing them, so this should be resolved. Also, please attach a file that you have tried for us to test and confirm if everything is working fine as intended.

**Comment by NRayya** [comment]
Uploading projects with trailing space and jdx and jdf files is working now
