### ISSUE TITLE
Suggestion to add the short version -  CC licenses

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#563]
License: For CC licenses, Add the short version, e.g. “Creative Commons Attribution 4.0 International” to “Creative Commons Attribution 4.0 International (CC BY 4.0)”.

**Comment by tilfischer** [comment]
To have it shorter one could substitute e.g. "“Creative Commons Attribution 4.0 International" with "CC BY 4.0". 

Currently, there is a long list of licenses one might choose. The first question one might ask is watching this list: Do we need this? Why do we need this and what for do we need this?

Checking out other NFDI4Chem repositories such as Chemotion Repository or RADAR(4Chem) there are usually only the CC licenses available and possibly the option to pick "other", which gives a free text field with a template stating that this is not recommended but researchers are again asked to pick a CC license.

Also with scientific publishing, the CC licenses are most common because they are sufficient.

**Comment by NRayya** [comment]
Good evening Tillmann,

The discussion about what license to keep and what to remove is still open in nmrXiv. In the docs you can find all the licenses that we believe to be relevant https://docs.nmrxiv.org/docs/submission-guides/licenses 

In the GitHub discussion, we mentioned the ones we are thinking of removing: https://github.com/NFDI4Chem/nmrxiv/discussions/123 

Could you please give those two resources a look and give us a final opinion whether you still believe CC is the only relevant one? 

I would say the answer for why we need several licenses is simply because "they are out there" and to get into the exact details of how they differ requires a legal consultation (not only from our end, but also from the user end). So as long as the license is for data publishing, we think we should make it available for the users to choose instead of forcing one option.

We also encountered the situation where data was licensed with software licenses such as MIT as the data was provided along with code on GitHub. And here we have to ask, do we have the right to convert licenses on our own as long as both licenses enable open sharing?

**Comment by tilfischer** [comment]
CC licenses are not necessarily the only relevant licenses. Just because licenses "are out there" does not mean that they need to be used in nmrXiv. The main questions are: 1) Do we need this? 2) For what and for whom do we need this?

As nmrXiv is a field-specific repository for NMR data only licenses for research data should be relevant and added. Moreover, we need to question with which licenses researchers are already most familiar with and, finally, if there is a benefit to add more licenses to this list. 

For your last question I would say: Possibly not.
