### ISSUE TITLE
Authors component

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#565]
The thing previously called ORCID ID (= Open Researcher and Contributor ID ID)  was replaced with ORCiD. Shall one add the URL or the URN or…?

The template for the affiliations does not have spaces after each comma. Is that intended? If yes, it should be stated that there should not be a space after the comma. If not, please change the template. Instead of affiliation, we should ask for the [ROR](https://ror.org/), e.g. https://ror.org/01mzk5576 

There should be the possibility to change the order the authors mentioned. This can only be done by manually editing and saving the authors again and considering the ordering. By doing so, I figured out that I couldn’t change the affiliation by editing and saving the data again. Hence, some authors are from a place in Germany, while for others, I could not specify this anymore.

**Comment by NishaSharma14** [comment]
The above points are fixed as part of refactoring the author's code., except for changing the template to ask for [ROR](https://ror.org/) instead of affiliation, which could be tracked as part of a separate issue [here](https://github.com/NFDI4Chem/nmrxiv/issues/608).

[screen-capture (5).webm](https://user-images.githubusercontent.com/54287612/202407332-03e15e70-c1d6-4753-9b23-a5b2053e0e9c.webm)

**Comment by tilfischer** [comment]
Great! Thank you!
