### ISSUE TITLE
ordering of authors (citations) shown on project (study) page does not reflect actual ordering

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#674]
The ordering of authors (and citations) on the project (study) page does not reflect the actual ordering. Example:

Project (study) page:

![nmrXiv_AuthorsCitation_Ordering1](https://user-images.githubusercontent.com/85482437/207056726-5dac08e6-4a28-4485-ad92-333cd1d14bec.PNG)

Actual ordering of the authors:

![nmrXiv_AuthorsCitation_Ordering2](https://user-images.githubusercontent.com/85482437/207056791-aacb2a45-6493-44b0-92c2-a33d57ea0210.PNG)

Same applies for the citations.

**Comment by NishaSharma14** [comment]
Dear @tilfischer ,

This issue is already addressed and fixed in our [dev](https://dev.nmrxiv.org/dashboard) branch as part of the [Issue](https://github.com/NFDI4Chem/nmrxiv/issues/654)

But to be fixed in [prod](https://nmrxiv.org/), it will take time as the deployment to prod is on hold (unless there are any breaking changes) until Chandu is back from leave.

For now to overcome this reloading the page will help.

Thanks for reporting this.
