### ISSUE TITLE
search function - looking up a search term gives 404 error 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#846]
Tying in the search bar, the user gets some suggestions to jump to, however, if they just type and press enter, they get 404 instead of a page with search results

**Comment by tilfischer** [comment]
I can report the same:

**Describe the bug and how to Reproduce**

Tested the search functionality of nmrXiv. Seaching via InChIKey e.g. 

```
DGQLVPJVXFOQEV-JNVSTXMASA-N
````

by adding this to the search field previews, as expected, Karminsäure. Clicking on "Karminsäure" preview or just press return gives a 404.


The same happens if the SMILES e.g. 

```CC1=C2C(=CC(=C1C(=O)O)O)C(=O)C3=C(C2=O)C(=C(C(=C3O)O)[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O
OC(C(C(C1=C2C)=O)=C3C(C1=CC(O)=C2C(O)=O)=O)=C(C(O)=C3O)[C@@H]4O[C@@H]([C@H]([C@@H]([C@H]4O)O)O)CO
``` 

 is used. 

Slight different behaviour is observed for InChI e.g.

```
InChI=1S/C22H20O13/c1-4-8-5(2-6(24)9(4)22(33)34)13(25)10-11(15(8)27)16(28)12(18(30)17(10)29)21-20(32)19(31)14(26)7(3-23)35-21/h2,7,14,19-21,23-24,26,28-32H,3H2,1H3,(H,33,34)/t7-,14-,19+,20-,21+/m1/s1
```

that it does not show Karminsäure as a preview. The same applies to Pulegon with 

```
NZGWDASTMWDZIW-MRVPVSSYSA-N
```
as InChIKey, while I havn't tested SMILES and InChI.

**Expected behavior**
Search via InChIKey, SMILES and InChI leads to the corresponding page of that structure or shows a list of search results, if there is more than one result. 

**Desktop:**
 - OS: Windows 11
 - Browser Brave/Chrome 
 - Version [Version 1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit)](https://brave.com/latest/) / Version 119.0.6045.200 (Official Build) (64-bit)

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Hi @tilfischer ,

Right now the search functionality is segregated requiring users to look up terms in the search panel of specific pages for individual components. 
For instance, if you wish to search using InchiKey, SMILES, and InCI, you must utilize the search panel on the [Compound Page](https://nmrxiv.org/compounds). Similarly, the search panel on the [Project page](https://nmrxiv.org/projects) exclusively provides results for projects, and the same applies to the [Spectra](https://nmrxiv.org/spectra) page.

Moreover, the search bar located at the top of each page is currently limited to Project search, but we plan to expand its functionality in the future.

We agree that right now it's a bit confusing, and we have plans in the future to merge these search functionalities into a more user-friendly, centralized point.
